version: '3'

volumes:
  mongodb:

networks:
  psocket:

services:
  psockets:
    container_name: psockets
    image: vspetini/psockets:v2.0.0
    networks:
      - psocket
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
      - redis
    environment:
      - APP_PORT=5000
      - SOCKET_PORT=5001

      - DATABASE_URL=mongodb://user:pass@mongodb:27017/psockets
      - HTTP_PORT=3000
      - JWT_SECRET=xsg1gasgasdafagaga
      - REDIS_URL=localhost:6379

      - DB_HOST=mongodb
      - DB_DATABASE=psockets
      - DB_USER=admin
      - DB_PASSWORD=pass
      
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  psockets-client:
    container_name: psockets-client
    image: vspetini/psockets-client:v2.0.0
    networks:
      - psocket
    ports:
      - "3000:3000"
    depends_on:
      - psockets
    environment:
      - NEXT_PUBLIC_APP=psockets
      - NEXT_PUBLIC_API_HOST=https://api.artesanaldoceria.roboticsmind.com.br
      - NEXT_PUBLIC_APP_ENV=development


  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodb:/data/db
    networks:
      - psocket
    ports:
      - "27017:27017"

  redis:
    container_name: redis
    image: redis:alpine
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - "6379:6379"
    restart: always
    networks:
      - psocket

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb
    networks:
      - psocket
